---
language: go
sudo: false
go:
  - 1.7.3
  - 1.8.1
  - tip

matrix:
  allow_failures:
    - go: tip

install:
  - go get -u ./...
  - go get -u gopkg.in/stretchr/testify.v1/assert

script:
  - go test -v
